name: Build OrangeFox

on:
  workflow_dispatch:
    inputs:
      SYNC_URL:
        description: Sync URL
        required: true
        default: 'https://gitlab.com/OrangeFox/sync.git'
      MANIFEST_BRANCH:
        description: Manifest Branch
        required: true
        default: '12.1'
      DEVICE_TREE_URL:
        description: Device Tree URL
        required: true
        default: 'https://github.com/saadelasfur/orangefox_device_samsung_m52xq.git'
      DEVICE_TREE_BRANCH:
        description: Device Tree Branch
        required: true
        default: 'fox_12.1'
      DEVICE_PATH:
        description: Device Path
        required: true
        default: 'device/samsung/m52xq'
      DEVICE_NAME:
        description: Device Name
        required: true
        default: 'm52xq'
      MAKEFILE_NAME:
        description: Makefile Name
        required: true
        default: 'twrp_m52xq'
      BUILD_TARGET:
        description: Build Target
        required: true
        default: 'recovery'
      OFOX_VERSION:
        description: OFOX Version
        required: true
        default: 'R11.1_1_A14-Stable'

jobs:
  build:
    if: github.event.repository.owner.id == github.event.sender.id
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Display Run Parameters
      run: |
        echo "::group::User Environment Variables"
        echo "Sync URL: ${{ github.event.inputs.SYNC_URL }}"
        echo "Manifest Branch: ${{ github.event.inputs.MANIFEST_BRANCH }}"
        echo "Device Tree URL: ${{ github.event.inputs.DEVICE_TREE_URL }}"
        echo "Device Tree Branch: ${{ github.event.inputs.DEVICE_TREE_BRANCH }}"
        echo "Device Path: ${{ github.event.inputs.DEVICE_PATH }}"
        echo "Device Name: ${{ github.event.inputs.DEVICE_NAME }}"
        echo "Makefile Name: ${{ github.event.inputs.MAKEFILE_NAME }}"
        echo "Build Target: ${{ github.event.inputs.BUILD_TARGET }}.img"
        echo "OFOX Version: ${{ github.event.inputs.OFOX_VERSION }}"
        echo "::endgroup::"

    - name: Check Out
      uses: actions/checkout@v4

    - name: Cleanup
      uses: rokibhasansagar/slimhub_actions@main

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 'latest'

    - name: Install OpenJDK
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '11'

    - name: Initialize workspace
      run: |
        mkdir workspace
        cd workspace
        echo "workspace-folder=$(pwd)" >> $GITHUB_OUTPUT
      id: pwd

    - name: Prepare the build environment
      run: |
        sudo apt-get update
        sudo apt-get -y upgrade
        sudo apt-get -y install git python3 tar aria2
        git clone https://gitlab.com/OrangeFox/misc/scripts.git
        cd scripts
        sudo bash setup/android_build_env.sh
        sed -i 's/cd -/cd ../g' setup/install_android_sdk.sh
        sudo bash setup/install_android_sdk.sh
      working-directory: ${{ steps.pwd.outputs.workspace-folder }}

    - name: Sync OrangeFox sources and minimal manifest
      run: |
        cd ${{ steps.pwd.outputs.workspace-folder }}
        git clone ${{ github.event.inputs.SYNC_URL }}
        cd sync
        ./orangefox_sync.sh --branch ${{ github.event.inputs.MANIFEST_BRANCH }} --path ${{ steps.pwd.outputs.workspace-folder }}/fox_${{ github.event.inputs.MANIFEST_BRANCH }}
      working-directory: ${{ steps.pwd.outputs.workspace-folder }}

    - name: Clone device tree
      run: |
        cd ${{ steps.pwd.outputs.workspace-folder }}/fox_${{ github.event.inputs.MANIFEST_BRANCH }}
        git clone ${{ github.event.inputs.DEVICE_TREE_URL }} -b ${{ github.event.inputs.DEVICE_TREE_BRANCH }} ./${{ github.event.inputs.DEVICE_PATH }}
      working-directory: ${{ steps.pwd.outputs.workspace-folder }}

    - name: Set Swap Space
      uses: pierotofy/set-swap-space@master
      with:
        swap-size-gb: 12

    - name: Building recovery
      run: |
        cd ${{ steps.pwd.outputs.workspace-folder }}/fox_${{ github.event.inputs.MANIFEST_BRANCH }}
        set +e
        export ALLOW_MISSING_DEPENDENCIES=true
        export FOX_BUILD_DEVICE=${{ github.event.inputs.DEVICE_NAME }}
        source build/envsetup.sh
        set -e
        lunch ${{ github.event.inputs.MAKEFILE_NAME }}-eng && make clean && mka adbd ${{ github.event.inputs.BUILD_TARGET }}image -j$(nproc --all)
      working-directory: ${{ steps.pwd.outputs.workspace-folder }}
      continue-on-error: true

    - name: Set Date Variables
      run: |
        echo "DATE_SHORT=$(date +%Y%m%d)" >> $GITHUB_OUTPUT
        echo "DATE_TAG=$(date +%Y%m%d%H%M%S)" >> $GITHUB_OUTPUT
        echo "DATE_LONG=$(date +%Y%m%d-%H%M)" >> $GITHUB_OUTPUT
      id: date

    - name: Archive the files
      run: |
        ls -a ${{ steps.pwd.outputs.workspace-folder }}/fox_${{ github.event.inputs.MANIFEST_BRANCH }}/out/target/product/ && echo
        ls -a ${{ steps.pwd.outputs.workspace-folder }}/fox_${{ github.event.inputs.MANIFEST_BRANCH }}/out/target/product/${{ github.event.inputs.DEVICE_NAME }}/ && echo
        cd ${{ steps.pwd.outputs.workspace-folder }}/fox_${{ github.event.inputs.MANIFEST_BRANCH }}/out/target/product/${{ github.event.inputs.DEVICE_NAME }}
        tar -cvf OrangeFox-${{ github.event.inputs.OFOX_VERSION }}-${{ github.event.inputs.DEVICE_NAME }}.tar ${{ github.event.inputs.BUILD_TARGET }}.img
        mv ${{ github.event.inputs.BUILD_TARGET }}.img OrangeFox-${{ github.event.inputs.OFOX_VERSION }}-${{ github.event.inputs.DEVICE_NAME }}.img
        # mv OrangeFox*.zip OrangeFox-${{ github.event.inputs.OFOX_VERSION }}-${{ github.event.inputs.DEVICE_NAME }}.zip
      working-directory: ${{ steps.pwd.outputs.workspace-folder }}

    - name: Upload to Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          ${{ steps.pwd.outputs.workspace-folder }}/fox_${{ github.event.inputs.MANIFEST_BRANCH }}/out/target/product/${{ github.event.inputs.DEVICE_NAME }}/OrangeFox-${{ github.event.inputs.OFOX_VERSION }}-${{ github.event.inputs.DEVICE_NAME }}.img
          ${{ steps.pwd.outputs.workspace-folder }}/fox_${{ github.event.inputs.MANIFEST_BRANCH }}/out/target/product/${{ github.event.inputs.DEVICE_NAME }}/OrangeFox-${{ github.event.inputs.OFOX_VERSION }}-${{ github.event.inputs.DEVICE_NAME }}.tar
          ${{ steps.pwd.outputs.workspace-folder }}/fox_${{ github.event.inputs.MANIFEST_BRANCH }}/out/target/product/${{ github.event.inputs.DEVICE_NAME }}/OrangeFox-${{ github.event.inputs.OFOX_VERSION }}-${{ github.event.inputs.DEVICE_NAME }}.zip
        name: ofox-${{ github.event.inputs.DEVICE_NAME }}-${{ steps.date.outputs.DATE_SHORT }}
        tag_name: ${{ steps.date.outputs.DATE_TAG }}
        body: |
          Manifest: ${{ github.event.inputs.MANIFEST_BRANCH }}
          Device: ${{ github.event.inputs.DEVICE_NAME }}
          Target: ${{ github.event.inputs.BUILD_TARGET }}
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
